### ISSUE TITLE
Добавить в образы net-tools

### ISSUE THREAD

**Issue by ovcharenko-di** [firstBitMarksistskaya/onec-docker#10]
VA не удается выполнить команду netstat из-за отсутствующего пакета net-tools

![image](https://user-images.githubusercontent.com/24920942/163212522-80208b35-5190-4161-a9ea-f1b214af4284.png)

Добавить в [этот](https://github.com/firstBitMarksistskaya/onec-docker/blob/feature/first-bit/test-utils/Dockerfile) файл

**Comment by nixel2007** [comment]
Closed by cab17c4
