### ISSUE TITLE
Ресурс для сборки jdk adoptopenjdk.jfrog.io не доступен

### ISSUE THREAD

**Issue by TABWorkGit** [firstBitMarksistskaya/onec-docker#28]
Для сборки jdk/Dockerfile ресурс  adoptopenjdk.jfrog.io не доступен возвращает 400 или 404

![image](https://github.com/firstBitMarksistskaya/onec-docker/assets/102640534/50aa7908-b176-4650-a73a-e4ca635c1c46)

**Comment by nixel2007** [comment]
Эх, дропнули таки. Надо переводить на temurin
