### ISSUE TITLE
Ошибка про сборке client-vnc. Библиотека libwebkitgtk

### ISSUE THREAD

**Issue by TABWorkGit** [firstBitMarksistskaya/onec-docker#31]
При сборке client-vnc не находит библиотеку в репозитории. 
Она не требуется для платформ выше 8.3.20.1363. Убрали зависимость вроде как из-за проблем с безопасностью.

У себя поправил пока так. Я думаю для 8.3.20 можно и убрать вообще установку.
```
 Install libwebkitgtk from stretch
  #&& echo "deb http://deb.debian.org/debian/ stretch main contrib non-free" > /etc/apt/sources.list.d/stretch.list \
  && echo "deb http://archive.debian.org/debian/ stretch main contrib non-free" > /etc/apt/sources.list.d/stretch.list \
```

**Comment by nixel2007** [comment]
Добрый день. Это было исправлено буквально вчера :)

**Comment by TABWorkGit** [comment]
Понял, ну я видел что там висели PR, но их никто не принимал, поэтому пришлось у себя локально сделать
